{
	"version": 1692848043,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/egg-sheet0.png",
		"images/egg-sheet1.png",
		"images/table.png",
		"images/cuttingboard-sheet0.png",
		"images/kattle-sheet0.png",
		"images/bowl-sheet0.png",
		"images/bowl-sheet1.png",
		"images/mama-sheet0.png",
		"images/mama-sheet1.png",
		"images/seasoning-sheet0.png",
		"images/seasoning-sheet1.png",
		"images/cap-sheet0.png",
		"images/refi-sheet0.png",
		"images/counter-sheet0.png",
		"images/counter-sheet1.png",
		"images/counter-sheet2.png",
		"images/bg-sheet0.png",
		"images/sisscor-sheet0.png",
		"images/box-sheet0.png",
		"images/ans-sheet0.png",
		"images/ans-sheet1.png",
		"images/fire.png",
		"images/switch-sheet0.png",
		"images/switch-sheet1.png",
		"media/yay sound effect (download) (1).m4a",
		"media/yay sound effect (download) (1).ogg",
		"media/pop.m4a",
		"media/pop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}